# Generated by Django 4.2.3 on 2023-07-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_oder_order_rename_oder_item_order_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information_customer',
            old_name='oder',
            new_name='order',
        ),
    ]
