# Generated by Django 4.2.3 on 2023-07-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_oder_information_customer_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information_customer',
            new_name='InformationCustomer',
        ),
        migrations.RenameModel(
            old_name='Order_item',
            new_name='OrderItem',
        ),
    ]
