# Generated by Django 5.2.6 on 2025-09-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_payment_vnpay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationCustomer',
        ),
    ]
