# Generated by Django 5.2.6 on 2025-09-29 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Ảnh phụ sản phẩm', 'verbose_name_plural': 'Ảnh phụ sản phẩm'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Mô tả ảnh (SEO / trợ năng)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
