# Generated by Django 5.2.6 on 2025-09-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_productimage_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Hộp'), ('box', 'Thùng')], default='piece', max_length=10),
        ),
    ]
