# Generated by Django 5.2.6 on 2025-09-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_productimage_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Ảnh phụ sản phẩm', 'verbose_name_plural': 'Ảnh phụ sản phẩm'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Mô tả ảnh (SEO / trợ năng)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/extra/'),
        ),
    ]
