# Generated by Django 5.2.6 on 2025-09-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_productimage_options_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
