# Generated by Django 5.2.6 on 2025-09-30 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_order_status_order_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='user',
        ),
        migrations.AddField(
            model_name='productreport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.order'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='reason',
            field=models.CharField(choices=[('fake', 'Hàng giả / nhái'), ('expired', 'Hết hạn sử dụng'), ('wrong', 'Sai thông tin'), ('other', 'Khác')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product'),
        ),
    ]
