# Generated by Django 5.2.6 on 2025-09-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='confirmed', max_length=20),
        ),
    ]
