# Generated by Django 5.2.6 on 2025-10-05 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_order_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('free_ship', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Hộp'), ('box', 'Thùng')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='apps.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='apps.product'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phường/Xã')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số nhà, đường...')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ đầy đủ')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
